module.exports = {
	ROBOT_NAME: '机器人小z',
	INIT_ROOM: 'VIP聊天',
	INIT_ROOM_INFO: '有问题欢迎发帖资讯',
	INIT_ADMIN_EMAIL: 'alphaz.cn',
	DEFAULT_AVATAR: 'http://oj7h98lzb.bkt.clouddn.com/user.svg',
	DEFAULT_GROUP_AVATAR: 'http://oj7h98lzb.bkt.clouddn.com/download.svg',
	DAY: 24*60*60*1000,
	JWT_KEY: 'JWT_KEY',
	ROBOT_URL: 'http://www.tuling123.com/openapi/api',
	ROBOT_KEY: '273e3ca4189a3fc03b4a94db8d87796b',
	ROBOT_AVATAR:'http://oajmk96un.bkt.clouddn.com/robot.jpg',
	QINIU_ACCESS_KEY: 'e48-XlFoDI86AmRWBvmPyUXQGGQUsNIHVz2t7RkH',
	QINIU_SECRET_KEY: 'uv7scH4ABVPQCh_8rVabeTW3S6Q74GPoiuhzkJtf',
	QINIU_CNAME: 'http://ozwz6xj3t.bkt.clouddn.com',
	QINIU_BUCKET: 'chat',
	MAX_ROOM: 5,
	MAX_BLOCK: 30,
}
